name: Test Action in Marketplace
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Run my own container action
        id: action
        uses: GitHubActionsInAction/ActionInAction@v1.2.1
        with:
          who-to-greet: '@wulfland'

      - name: Output the answer
        run: echo "The answer is ${{ steps.action.outputs.answer }}"